// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZaporArrow.DbContexts;

namespace ZaporArrow.Migrations
{
    [DbContext(typeof(ZaporArrowContext))]
    [Migration("20191106124842_fixedPicPathMigration")]
    partial class fixedPicPathMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZaporArrow.Entities.Arrow", b =>
                {
                    b.Property<Guid>("ArrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.HasKey("ArrowId");

                    b.ToTable("Arrows");

                    b.HasData(
                        new
                        {
                            ArrowId = new Guid("97bcd962-2a0d-4489-8e48-19dd2c848893"),
                            Description = "extra donga 7mm, 22 - 22, 2gramm 30 font!",
                            Length = 30.0
                        },
                        new
                        {
                            ArrowId = new Guid("e71847d9-1ddb-4db1-8af5-801803d6151c"),
                            Description = "35 font, 23g 0,3tized gramm szórásban. 8 ról 7es extra donga!",
                            Length = 29.5
                        },
                        new
                        {
                            ArrowId = new Guid("019e54c4-5a54-42d3-a78a-8b3d9dd0d85d"),
                            Description = "35#, 22,2-22,5g Extra dongás. (7mm)",
                            Length = 30.0
                        });
                });

            modelBuilder.Entity("ZaporArrow.Entities.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArrowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("ImageId");

                    b.HasIndex("ArrowId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("babbf4a6-d5ec-4054-b2e8-2b5c508a947a"),
                            ArrowId = new Guid("97bcd962-2a0d-4489-8e48-19dd2c848893"),
                            ImageSource = "/images/bfb1.jpg",
                            Size = 563.0
                        },
                        new
                        {
                            ImageId = new Guid("088f9fb0-70b6-49e0-b80a-cca1dd3c631a"),
                            ArrowId = new Guid("e71847d9-1ddb-4db1-8af5-801803d6151c"),
                            ImageSource = "/images/ujpest1.jpg",
                            Size = 467.0
                        },
                        new
                        {
                            ImageId = new Guid("211aee93-89cb-46d4-b946-e8f4c7d938c9"),
                            ArrowId = new Guid("019e54c4-5a54-42d3-a78a-8b3d9dd0d85d"),
                            ImageSource = "/images/svb1.jpg",
                            Size = 351.0
                        });
                });

            modelBuilder.Entity("ZaporArrow.Entities.Image", b =>
                {
                    b.HasOne("ZaporArrow.Entities.Arrow", null)
                        .WithMany("Images")
                        .HasForeignKey("ArrowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
